-- ============================================================
-- V001__init_schema.sql  最终表结构、约束、RLS 与运行时数据库权限（DDL）
-- ============================================================

-- ✅ 枚举类型定义
CREATE TYPE product_type AS ENUM ('MATERIAL', 'ASSET');
CREATE TYPE product_unit AS ENUM (
    'PIECE', 'BOX', 'PACK', 'DOZEN', 'PAIR', 'GRAM', 'KILOGRAM', 'LITER',
    'MILLILITER', 'METER', 'CENTIMETER', 'BOTTLE', 'BARREL', 'BAG', 'SHEET', 'ROLL', 'ITEM'
);
CREATE TYPE order_status AS ENUM ('PENDING', 'COMPLETED', 'CANCELED', 'REVERSED');
CREATE TYPE inventory_status AS ENUM ('NORMAL', 'CONSUMED', 'CANCELED', 'REVERSED');
CREATE TYPE inventory_unit_type AS ENUM ('INSTANCE', 'BATCH');
CREATE TYPE user_sex AS ENUM ('M', 'F');
CREATE TYPE feedback_category AS ENUM ('BUG', 'DATA_WRONG', 'USABILITY', 'FEATURE_REQUEST', 'OTHER');
CREATE TYPE feedback_status AS ENUM ('NEW', 'CONFIRMED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
CREATE TYPE feedback_source AS ENUM ('WEB', 'MOBILE');
CREATE TYPE tenant_status AS ENUM ('PENDING_ACTIVATION', 'ACTIVE', 'SUSPENDED', 'DEPROVISIONED');
CREATE TYPE membership_status AS ENUM ('ACTIVE', 'SUSPENDED', 'PENDING_INVITATION');
CREATE TYPE tenant_storage_mode AS ENUM ('SHARED_CELL', 'DEDICATED_DATABASE');

-- ✅ 用户与认证
CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    locked BOOLEAN NOT NULL,
    name VARCHAR(50) NOT NULL CONSTRAINT uq_user_account_name UNIQUE,
    nick VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    sex user_sex,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE user_external_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer VARCHAR(500) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL CONSTRAINT fk_user_external_identity_user_id REFERENCES user_account,
    email VARCHAR(320),
    display_name VARCHAR(255),
    provider VARCHAR(32),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    picture_url VARCHAR(1024),
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    profile_synced_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_external_identity_issuer_subject UNIQUE (issuer, subject)
);

-- ✅ 租户（必须在 tenant_role 之前，因为 tenant_role.tenant_id REFERENCES tenant）
CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(200),
    status tenant_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tenant_name UNIQUE (name)
);

CREATE TABLE tenant_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    user_id BIGINT NOT NULL REFERENCES user_account(id),
    status membership_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tenant_membership_tenant_user UNIQUE (tenant_id, user_id)
);

CREATE TABLE tenant_invitation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    email VARCHAR(320) NOT NULL,
    role_ids BIGINT[] NOT NULL DEFAULT '{}',
    invited_by_user_id BIGINT REFERENCES user_account(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    token VARCHAR(255) NOT NULL CONSTRAINT uq_tenant_invitation_token UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    initial_administrator BOOLEAN NOT NULL DEFAULT FALSE,
    accepted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE tenant_placement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id) CONSTRAINT uq_tenant_placement_tenant UNIQUE,
    cell_id VARCHAR(100) NOT NULL DEFAULT 'cell-default-01',
    storage_mode tenant_storage_mode NOT NULL DEFAULT 'SHARED_CELL',
    placement_version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ✅ 角色与权限（租户级）
CREATE TABLE tenant_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255),
    name VARCHAR(50) NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tenant_role_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    label VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_permission_name UNIQUE (name),
    CONSTRAINT ck_permission_scope CHECK (scope IN ('PLATFORM', 'TENANT', 'BUSINESS'))
);

CREATE TABLE tenant_role_permission (
    role_id BIGINT NOT NULL CONSTRAINT fk_tenant_role_permission_role_id REFERENCES tenant_role,
    permission_id BIGINT NOT NULL CONSTRAINT fk_tenant_role_permission_permission_id REFERENCES permission,
    PRIMARY KEY (role_id, permission_id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE tenant_membership_role (
    membership_id BIGINT NOT NULL REFERENCES tenant_membership(id),
    role_id BIGINT NOT NULL REFERENCES tenant_role(id),
    PRIMARY KEY (membership_id, role_id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ✅ 平台级角色与用户分配
CREATE TABLE platform_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    label VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_platform_role_name UNIQUE (name)
);

CREATE TABLE platform_role_permission (
    platform_role_id BIGINT NOT NULL REFERENCES platform_role(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permission(id),
    PRIMARY KEY (platform_role_id, permission_id)
);

CREATE TABLE platform_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
    platform_role_id BIGINT NOT NULL REFERENCES platform_role(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_platform_user_role UNIQUE (user_id, platform_role_id)
);

-- ✅ 产品
CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500),
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT CONSTRAINT fk_product_category_parent_id REFERENCES product_category,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_product_category_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    specification VARCHAR(50),
    barcode VARCHAR(100) NOT NULL,
    type product_type,
    unit product_unit NOT NULL,
    note TEXT,
    enabled BOOLEAN NOT NULL,
    category_id BIGINT NOT NULL CONSTRAINT fk_product_category_id REFERENCES product_category,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_product_tenant_barcode UNIQUE (tenant_id, barcode)
);

-- ✅ 库存
CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_stock BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    safety_stock BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_inventory_tenant_product UNIQUE (tenant_id, product_id)
);

CREATE TABLE inventory_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_type VARCHAR(31) NOT NULL,
    depot_id BIGINT,
    purchase_order_id BIGINT NOT NULL,
    initial_quantity BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    frozen_quantity BIGINT NOT NULL,
    received_at TIMESTAMP(6) WITH TIME ZONE,
    sale_order_ids BIGINT[],
    status inventory_status NOT NULL,
    unit_price NUMERIC(38, 2),
    version BIGINT NOT NULL,
    batch_code UUID,
    serial_number VARCHAR(255),
    inventory_id BIGINT CONSTRAINT fk_inventory_unit_inventory_id REFERENCES inventory,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_inventory_unit_tenant_serial UNIQUE (tenant_id, serial_number)
);

-- ✅ 采购
CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no UUID NOT NULL,
    note VARCHAR(255),
    order_date DATE,
    status order_status,
    supplier_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_purchase_order_tenant_no UNIQUE (tenant_id, no)
);

CREATE TABLE purchase_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    product_type product_type,
    quantity INTEGER NOT NULL,
    serial_number VARCHAR(255),
    unit_price NUMERIC(38, 2),
    order_id BIGINT CONSTRAINT fk_purchase_order_item_order_id REFERENCES purchase_order,
    batch_code UUID,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ✅ 销售
CREATE TABLE sale_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    no UUID NOT NULL,
    note VARCHAR(255),
    order_date DATE,
    status order_status,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_sale_order_tenant_no UNIQUE (tenant_id, no)
);

CREATE TABLE sale_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_unit_id BIGINT NOT NULL,
    inventory_unit_type inventory_unit_type,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(38, 2),
    order_id BIGINT CONSTRAINT fk_sale_order_item_order_id REFERENCES sale_order,
    discount_factor NUMERIC(38, 2),
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ✅ 合作伙伴
CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(200),
    enabled BOOLEAN NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(255),
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_customer_tenant_name UNIQUE (tenant_id, name, phone)
);

CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(200),
    contact_person VARCHAR(50),
    enabled BOOLEAN NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(255),
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_supplier_tenant_name UNIQUE (tenant_id, name, phone)
);

-- ✅ 仓库
CREATE TABLE depot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    location VARCHAR(200),
    name VARCHAR(100) NOT NULL,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_depot_tenant_name UNIQUE (tenant_id, name),
    -- 复合外键要求被引用的租户与仓库 ID 组合具有唯一约束。
    CONSTRAINT uq_depot_tenant_id UNIQUE (tenant_id, id)
);

-- 从数据库结构层保证库存只能关联同一租户的仓库。
ALTER TABLE inventory_unit
    ADD CONSTRAINT fk_inventory_unit_tenant_depot
        FOREIGN KEY (tenant_id, depot_id)
        REFERENCES depot (tenant_id, id);

-- ✅ 反馈
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category feedback_category NOT NULL,
    status feedback_status NOT NULL DEFAULT 'NEW',
    source feedback_source NOT NULL,
    title VARCHAR(120),
    description TEXT NOT NULL,
    page_path VARCHAR(512),
    app_version VARCHAR(64),
    platform VARCHAR(64),
    device_info TEXT,
    error_context TEXT,
    contact VARCHAR(120),
    allow_contact BOOLEAN NOT NULL DEFAULT TRUE,
    reporter_user_id BIGINT,
    assignee_user_id BIGINT,
    resolution_note TEXT,
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    image_urls JSONB NOT NULL DEFAULT '[]'::JSONB,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ✅ 索引
CREATE INDEX idx_feedback_status_created_at ON feedback (status, created_at DESC);
CREATE INDEX idx_feedback_source_created_at ON feedback (source, created_at DESC);
CREATE INDEX idx_feedback_reporter_created_at ON feedback (reporter_user_id, created_at DESC);
CREATE INDEX idx_feedback_category_status ON feedback (category, status);

CREATE INDEX idx_tenant_membership_user ON tenant_membership (user_id);
CREATE INDEX idx_tenant_membership_tenant ON tenant_membership (tenant_id);
CREATE INDEX idx_tenant_invitation_tenant_email ON tenant_invitation (tenant_id, email);

CREATE INDEX idx_tenant_role_tenant ON tenant_role (tenant_id);
CREATE INDEX idx_platform_user_role_user ON platform_user_role (user_id);
CREATE INDEX idx_platform_user_role_role ON platform_user_role (platform_role_id);
CREATE INDEX idx_product_category_tenant ON product_category (tenant_id);
CREATE INDEX idx_product_tenant ON product (tenant_id);
CREATE INDEX idx_inventory_tenant ON inventory (tenant_id);
CREATE INDEX idx_inventory_unit_tenant ON inventory_unit (tenant_id);
CREATE INDEX idx_purchase_order_tenant ON purchase_order (tenant_id);
CREATE INDEX idx_purchase_order_item_tenant ON purchase_order_item (tenant_id);
CREATE INDEX idx_sale_order_tenant ON sale_order (tenant_id);
CREATE INDEX idx_sale_order_item_tenant ON sale_order_item (tenant_id);
CREATE INDEX idx_customer_tenant ON customer (tenant_id);
CREATE INDEX idx_supplier_tenant ON supplier (tenant_id);
CREATE INDEX idx_depot_tenant ON depot (tenant_id);
CREATE INDEX idx_feedback_tenant ON feedback (tenant_id);

CREATE INDEX idx_product_tenant_category ON product (tenant_id, category_id);
CREATE INDEX idx_sale_order_tenant_status_date ON sale_order (tenant_id, status, order_date DESC);
CREATE INDEX idx_purchase_order_tenant_status_date ON purchase_order (tenant_id, status, order_date DESC);
CREATE INDEX idx_inventory_unit_tenant_inventory ON inventory_unit (tenant_id, inventory_id);
CREATE INDEX idx_feedback_tenant_status_created ON feedback (tenant_id, status, created_at DESC);
CREATE INDEX idx_customer_tenant_name ON customer (tenant_id, name);
CREATE INDEX idx_supplier_tenant_name ON supplier (tenant_id, name);
CREATE INDEX idx_depot_tenant_name ON depot (tenant_id, name);
CREATE INDEX idx_product_category_tenant_name ON product_category (tenant_id, name);

-- ✅ 序列重置
ALTER SEQUENCE user_account_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_role_id_seq RESTART WITH 100;
ALTER SEQUENCE permission_id_seq RESTART WITH 100;
ALTER SEQUENCE product_category_id_seq RESTART WITH 100;
ALTER SEQUENCE product_id_seq RESTART WITH 100;
ALTER SEQUENCE inventory_id_seq RESTART WITH 100;
ALTER SEQUENCE inventory_unit_id_seq RESTART WITH 100;
ALTER SEQUENCE purchase_order_id_seq RESTART WITH 100;
ALTER SEQUENCE sale_order_id_seq RESTART WITH 100;
ALTER SEQUENCE customer_id_seq RESTART WITH 100;
ALTER SEQUENCE supplier_id_seq RESTART WITH 100;
ALTER SEQUENCE depot_id_seq RESTART WITH 100;
ALTER SEQUENCE feedback_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_membership_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_invitation_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_placement_id_seq RESTART WITH 100;
ALTER SEQUENCE platform_role_id_seq RESTART WITH 100;
ALTER SEQUENCE platform_user_role_id_seq RESTART WITH 100;
