-- ============================================================
-- V005__create_tenant_tables.sql  租户相关表结构
-- ============================================================

-- 租户状态枚举
CREATE TYPE tenant_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DEPROVISIONED');

-- 成员状态枚举
CREATE TYPE membership_status AS ENUM ('ACTIVE', 'SUSPENDED', 'PENDING_INVITATION');

-- 存储模式枚举
CREATE TYPE tenant_storage_mode AS ENUM ('SHARED_CELL', 'DEDICATED_DATABASE');

-- 租户表
CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(200),
    status tenant_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tenant_name UNIQUE (name)
);

-- 租户成员表
CREATE TABLE tenant_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    user_id BIGINT NOT NULL REFERENCES user_account(id),
    status membership_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tenant_membership_tenant_user UNIQUE (tenant_id, user_id)
);

-- 租户成员角色表
CREATE TABLE tenant_membership_role (
    membership_id BIGINT NOT NULL REFERENCES tenant_membership(id),
    role_id BIGINT NOT NULL REFERENCES role(id),
    PRIMARY KEY (membership_id, role_id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 租户邀请表
CREATE TABLE tenant_invitation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id),
    email VARCHAR(320) NOT NULL,
    role_ids BIGINT[] NOT NULL DEFAULT '{}',
    invited_by_user_id BIGINT REFERENCES user_account(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    token VARCHAR(255) NOT NULL CONSTRAINT uq_tenant_invitation_token UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 租户位置表（未来 Cell 路由扩展点）
CREATE TABLE tenant_placement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL REFERENCES tenant(id) CONSTRAINT uq_tenant_placement_tenant UNIQUE,
    cell_id VARCHAR(100) NOT NULL DEFAULT 'cell-default-01',
    storage_mode tenant_storage_mode NOT NULL DEFAULT 'SHARED_CELL',
    placement_version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 索引
CREATE INDEX idx_tenant_membership_user ON tenant_membership (user_id);
CREATE INDEX idx_tenant_membership_tenant ON tenant_membership (tenant_id);
CREATE INDEX idx_tenant_invitation_tenant_email ON tenant_invitation (tenant_id, email);

-- 重置序列
ALTER SEQUENCE tenant_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_membership_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_invitation_id_seq RESTART WITH 100;
ALTER SEQUENCE tenant_placement_id_seq RESTART WITH 100;
