package org.abacusflow.usecase.commons.security

/** Immutable permission names deployed by Flyway and consumed by backend authorization contracts. */
object PermissionNames {
    object Platform {
        const val TENANT_LIST = "platform:tenant:list"
        const val TENANT_CREATE = "platform:tenant:create"
        const val TENANT_UPDATE = "platform:tenant:update"
        const val TENANT_DELETE = "platform:tenant:delete"
        const val USER_READ = "platform:user:read"
        const val USER_MANAGE = "platform:user:manage"
        const val PERMISSION_READ = "platform:permission:read"
        const val PERMISSION_MANAGE = "platform:permission:manage"
        const val ROLE_READ = "platform:role:read"
        const val ROLE_MANAGE = "platform:role:manage"
    }

    object Tenant {
        const val PROFILE_READ = "tenant:profile:read"
        const val PROFILE_UPDATE = "tenant:profile:update"
        const val MEMBER_READ = "tenant:member:read"
        const val MEMBER_CREATE = "tenant:member:create"
        const val MEMBER_UPDATE = "tenant:member:update"
        const val MEMBER_REMOVE = "tenant:member:remove"
        const val ROLE_READ = "tenant:role:read"
        const val ROLE_MANAGE = "tenant:role:manage"
    }

    object Business {
        const val PRODUCT_READ = "business:product:read"
        const val PRODUCT_CREATE = "business:product:create"
        const val PRODUCT_UPDATE = "business:product:update"
        const val PRODUCT_DELETE = "business:product:delete"
        const val PRODUCT_CATEGORY_READ = "business:product-category:read"
        const val PRODUCT_CATEGORY_CREATE = "business:product-category:create"
        const val PRODUCT_CATEGORY_UPDATE = "business:product-category:update"
        const val PRODUCT_CATEGORY_DELETE = "business:product-category:delete"
        const val PURCHASE_ORDER_READ = "business:purchase-order:read"
        const val PURCHASE_ORDER_CREATE = "business:purchase-order:create"
        const val PURCHASE_ORDER_APPROVE = "business:purchase-order:approve"
        const val SALE_ORDER_READ = "business:sale-order:read"
        const val SALE_ORDER_CREATE = "business:sale-order:create"
        const val SALE_ORDER_APPROVE = "business:sale-order:approve"
        const val INVENTORY_READ = "business:inventory:read"
        const val INVENTORY_UPDATE = "business:inventory:update"
        const val INVENTORY_UNIT_READ = "business:inventory-unit:read"
        const val INVENTORY_UNIT_UPDATE = "business:inventory-unit:update"
        const val DEPOT_READ = "business:depot:read"
        const val DEPOT_CREATE = "business:depot:create"
        const val DEPOT_UPDATE = "business:depot:update"
        const val DEPOT_DELETE = "business:depot:delete"
        const val CUSTOMER_READ = "business:customer:read"
        const val CUSTOMER_CREATE = "business:customer:create"
        const val CUSTOMER_UPDATE = "business:customer:update"
        const val CUSTOMER_DELETE = "business:customer:delete"
        const val SUPPLIER_READ = "business:supplier:read"
        const val SUPPLIER_CREATE = "business:supplier:create"
        const val SUPPLIER_UPDATE = "business:supplier:update"
        const val SUPPLIER_DELETE = "business:supplier:delete"
        const val FEEDBACK_READ = "business:feedback:read"
        const val FEEDBACK_CREATE = "business:feedback:create"
        const val FEEDBACK_UPDATE = "business:feedback:update"
    }
}

/** Compile-time SpEL expressions used by method-security annotations. */
object RequiredAuthority {
    const val PLATFORM_TENANT_LIST = "hasAuthority('" + PermissionNames.Platform.TENANT_LIST + "')"
    const val PLATFORM_TENANT_CREATE = "hasAuthority('" + PermissionNames.Platform.TENANT_CREATE + "')"
    const val PLATFORM_TENANT_UPDATE = "hasAuthority('" + PermissionNames.Platform.TENANT_UPDATE + "')"
    const val PLATFORM_USER_READ = "hasAuthority('" + PermissionNames.Platform.USER_READ + "')"
    const val PLATFORM_USER_MANAGE = "hasAuthority('" + PermissionNames.Platform.USER_MANAGE + "')"
    const val PLATFORM_PERMISSION_READ = "hasAuthority('" + PermissionNames.Platform.PERMISSION_READ + "')"
    const val PLATFORM_PERMISSION_MANAGE = "hasAuthority('" + PermissionNames.Platform.PERMISSION_MANAGE + "')"
    const val PLATFORM_ROLE_READ = "hasAuthority('" + PermissionNames.Platform.ROLE_READ + "')"
    const val PLATFORM_ROLE_MANAGE = "hasAuthority('" + PermissionNames.Platform.ROLE_MANAGE + "')"

    const val TENANT_PROFILE_READ = "hasAuthority('" + PermissionNames.Tenant.PROFILE_READ + "')"
    const val TENANT_PROFILE_UPDATE = "hasAuthority('" + PermissionNames.Tenant.PROFILE_UPDATE + "')"
    const val TENANT_MEMBER_READ = "hasAuthority('" + PermissionNames.Tenant.MEMBER_READ + "')"
    const val TENANT_MEMBER_CREATE = "hasAuthority('" + PermissionNames.Tenant.MEMBER_CREATE + "')"
    const val TENANT_MEMBER_UPDATE = "hasAuthority('" + PermissionNames.Tenant.MEMBER_UPDATE + "')"
    const val TENANT_MEMBER_REMOVE = "hasAuthority('" + PermissionNames.Tenant.MEMBER_REMOVE + "')"
    const val TENANT_ROLE_READ = "hasAuthority('" + PermissionNames.Tenant.ROLE_READ + "')"
    const val TENANT_ROLE_MANAGE = "hasAuthority('" + PermissionNames.Tenant.ROLE_MANAGE + "')"

    const val BUSINESS_PRODUCT_READ = "hasAuthority('" + PermissionNames.Business.PRODUCT_READ + "')"
    const val BUSINESS_PRODUCT_CREATE = "hasAuthority('" + PermissionNames.Business.PRODUCT_CREATE + "')"
    const val BUSINESS_PRODUCT_UPDATE = "hasAuthority('" + PermissionNames.Business.PRODUCT_UPDATE + "')"
    const val BUSINESS_PRODUCT_DELETE = "hasAuthority('" + PermissionNames.Business.PRODUCT_DELETE + "')"
    const val BUSINESS_PRODUCT_CATEGORY_READ = "hasAuthority('" + PermissionNames.Business.PRODUCT_CATEGORY_READ + "')"
    const val BUSINESS_PRODUCT_CATEGORY_CREATE = "hasAuthority('" + PermissionNames.Business.PRODUCT_CATEGORY_CREATE + "')"
    const val BUSINESS_PRODUCT_CATEGORY_UPDATE = "hasAuthority('" + PermissionNames.Business.PRODUCT_CATEGORY_UPDATE + "')"
    const val BUSINESS_PRODUCT_CATEGORY_DELETE = "hasAuthority('" + PermissionNames.Business.PRODUCT_CATEGORY_DELETE + "')"
    const val BUSINESS_PURCHASE_ORDER_READ = "hasAuthority('" + PermissionNames.Business.PURCHASE_ORDER_READ + "')"
    const val BUSINESS_PURCHASE_ORDER_CREATE = "hasAuthority('" + PermissionNames.Business.PURCHASE_ORDER_CREATE + "')"
    const val BUSINESS_PURCHASE_ORDER_APPROVE = "hasAuthority('" + PermissionNames.Business.PURCHASE_ORDER_APPROVE + "')"
    const val BUSINESS_SALE_ORDER_READ = "hasAuthority('" + PermissionNames.Business.SALE_ORDER_READ + "')"
    const val BUSINESS_SALE_ORDER_CREATE = "hasAuthority('" + PermissionNames.Business.SALE_ORDER_CREATE + "')"
    const val BUSINESS_SALE_ORDER_APPROVE = "hasAuthority('" + PermissionNames.Business.SALE_ORDER_APPROVE + "')"
    const val BUSINESS_INVENTORY_READ = "hasAuthority('" + PermissionNames.Business.INVENTORY_READ + "')"
    const val BUSINESS_INVENTORY_UPDATE = "hasAuthority('" + PermissionNames.Business.INVENTORY_UPDATE + "')"
    const val BUSINESS_INVENTORY_UNIT_READ = "hasAuthority('" + PermissionNames.Business.INVENTORY_UNIT_READ + "')"
    const val BUSINESS_INVENTORY_UNIT_UPDATE = "hasAuthority('" + PermissionNames.Business.INVENTORY_UNIT_UPDATE + "')"
    const val BUSINESS_DEPOT_READ = "hasAuthority('" + PermissionNames.Business.DEPOT_READ + "')"
    const val BUSINESS_DEPOT_CREATE = "hasAuthority('" + PermissionNames.Business.DEPOT_CREATE + "')"
    const val BUSINESS_DEPOT_UPDATE = "hasAuthority('" + PermissionNames.Business.DEPOT_UPDATE + "')"
    const val BUSINESS_DEPOT_DELETE = "hasAuthority('" + PermissionNames.Business.DEPOT_DELETE + "')"
    const val BUSINESS_CUSTOMER_READ = "hasAuthority('" + PermissionNames.Business.CUSTOMER_READ + "')"
    const val BUSINESS_CUSTOMER_CREATE = "hasAuthority('" + PermissionNames.Business.CUSTOMER_CREATE + "')"
    const val BUSINESS_CUSTOMER_UPDATE = "hasAuthority('" + PermissionNames.Business.CUSTOMER_UPDATE + "')"
    const val BUSINESS_CUSTOMER_DELETE = "hasAuthority('" + PermissionNames.Business.CUSTOMER_DELETE + "')"
    const val BUSINESS_SUPPLIER_READ = "hasAuthority('" + PermissionNames.Business.SUPPLIER_READ + "')"
    const val BUSINESS_SUPPLIER_CREATE = "hasAuthority('" + PermissionNames.Business.SUPPLIER_CREATE + "')"
    const val BUSINESS_SUPPLIER_UPDATE = "hasAuthority('" + PermissionNames.Business.SUPPLIER_UPDATE + "')"
    const val BUSINESS_SUPPLIER_DELETE = "hasAuthority('" + PermissionNames.Business.SUPPLIER_DELETE + "')"
    const val BUSINESS_FEEDBACK_READ = "hasAuthority('" + PermissionNames.Business.FEEDBACK_READ + "')"
    const val BUSINESS_FEEDBACK_CREATE = "hasAuthority('" + PermissionNames.Business.FEEDBACK_CREATE + "')"
    const val BUSINESS_FEEDBACK_UPDATE = "hasAuthority('" + PermissionNames.Business.FEEDBACK_UPDATE + "')"
}
