-- Migration CLI 自己的控制面，不属于 AbacusFlow 业务 schema。
-- 本脚本由运维显式审核/执行；骨架阶段不会自动修改任何数据库。
CREATE SCHEMA IF NOT EXISTS abacusflow_migration;

-- 迁移锁：防止多个迁移实例同时执行
CREATE TABLE IF NOT EXISTS abacusflow_migration.migration_lock (
    lock_id INTEGER PRIMARY KEY DEFAULT 1,
    acquired_at TIMESTAMPTZ NOT NULL,
    acquired_by VARCHAR(255) NOT NULL,
    CONSTRAINT ck_migration_lock_single_row CHECK (lock_id = 1)
);

CREATE TABLE IF NOT EXISTS abacusflow_migration.migration_run (
    run_id UUID PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    selected_tasks JSONB NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    message TEXT,
    CONSTRAINT ck_migration_run_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS abacusflow_migration.migration_task_run (
    run_id UUID NOT NULL REFERENCES abacusflow_migration.migration_run(run_id),
    task_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    processed_count BIGINT NOT NULL DEFAULT 0,
    skipped_count BIGINT NOT NULL DEFAULT 0,
    error_count BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    PRIMARY KEY (run_id, task_name)
);

-- task + stream 支持一个任务迁多张表；cursor 支持 Long、UUID 或复合业务键。
CREATE TABLE IF NOT EXISTS abacusflow_migration.migration_checkpoint (
    task_name VARCHAR(100) NOT NULL,
    stream VARCHAR(100) NOT NULL,
    cursor TEXT,
    processed_count BIGINT NOT NULL DEFAULT 0,
    run_id UUID NOT NULL REFERENCES abacusflow_migration.migration_run(run_id),
    implementation_version INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (task_name, stream)
);

CREATE TABLE IF NOT EXISTS abacusflow_migration.migration_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES abacusflow_migration.migration_run(run_id),
    task_name VARCHAR(100) NOT NULL,
    stream VARCHAR(100) NOT NULL,
    record_key TEXT NOT NULL,
    message TEXT NOT NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_migration_error_run_task
    ON abacusflow_migration.migration_error (run_id, task_name);

-- V1 → V2 ID 映射表：所有基础数据通过映射表转换，不直接保留 V1 ID
CREATE TABLE IF NOT EXISTS abacusflow_migration.v1_user_id_map (
    v1_user_id BIGINT PRIMARY KEY,
    v2_user_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS abacusflow_migration.v1_role_id_map (
    v1_role_id BIGINT PRIMARY KEY,
    v2_role_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS abacusflow_migration.v1_permission_id_map (
    v1_permission_id BIGINT PRIMARY KEY,
    v2_permission_id BIGINT NOT NULL
);
